name = "SecondQuantization"
uuid = "4bb1b9ef-2e6a-400a-895b-40086f502bb4"
authors = ["Alberto Mercurio"]
version = "0.1.0"

[deps]
DynamicPolynomials = "7c1d4256-1411-5781-91ec-d7bc3513ac07"
Latexify = "23fbe1c1-3f47-55db-b15f-69d7ec21a316"
SymbolicUtils = "d1185830-fcd6-423d-90d6-eec64667417b"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"
TermInterface = "8ea1fca8-c5ef-4a55-8b96-4e9afe9c9a3c"

[compat]
Latexify = "0.15"
SymbolicUtils = "0.14 - 0.19"
TermInterface = "0.2 - 0.3"
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
